(function(g){var window=this;var ZAa=function(a,b,c,d){var e=b.Wb();g.S(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.Zc(c,d?d:"mqdefault.jpg");var k=b instanceof g.jO?g.BV(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.EQ(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.jO?b.ua:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,aria_label:b.lk||g.T("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Kk(c),is_live:m,
is_list:l,is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.GQ&&(c.playlist_length=b.getLength());a.update(c)},C5=function(a,b){g.xH.call(this,{G:"div",
ba:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.created=!1},D5=function(a){var b={G:"span",
M:"ytp-upnext-top",J:[{G:"span",M:"ytp-upnext-header",J:[g.T("YTP_PLAYLIST_UP_NEXT")]},{G:"span",M:"ytp-upnext-title",J:["{{title}}"]},{G:"span",M:"ytp-upnext-author",J:["{{author}}"]}]},c={role:"button",href:"{{url}}","aria-label":g.T("YTP_AUTOPLAY_NEXT")};b={G:"div",M:"ytp-upnext",P:{"aria-label":"{{aria_label}}"},J:[{G:"div",M:"ytp-cued-thumbnail-overlay-image",P:{style:"{{background}}"}},b,{G:"a",M:"ytp-upnext-autoplay-icon",P:c,J:[{G:"svg",P:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
J:[{G:"circle",M:"ytp-svg-autoplay-circle",P:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",M:"ytp-svg-autoplay-ring",P:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",M:"ytp-svg-fill",P:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",M:"ytp-upnext-bottom",J:[{G:"span",M:"ytp-upnext-cancel"},{G:"span",M:"ytp-upnext-paused",
J:[g.T("YTP_AUTOPLAY_PAUSED_3")]}]}]};g.V.call(this,b);this.B=null;b=this.g["ytp-upnext-cancel"];this.B=new g.V({G:"button",ba:["ytp-upnext-cancel-button","ytp-button"],P:{tabindex:"0","aria-label":g.T("YTP_AUTOPLAY_CANCEL")},J:[g.T("YTP_CANCEL")]});g.M(this,this.B);this.B.U("click",this.oP,this);this.B.pa(b);this.o=a;this.K=this.g["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.H=new g.Zt(this.Tm,5E3,this);g.M(this,this.H);this.I=0;this.O(this.g["ytp-upnext-autoplay-icon"],"click",
this.xR);this.iB();this.O(a,"autonavvisibility",this.iB);this.O(a,"mdxnowautoplaying",this.MQ);this.O(a,"mdxautoplaycanceled",this.NQ);this.O(a,"mdxautoplayupnext",this.LD);3==this.o.Qa()&&(a=(a=g.HU(g.CU(this.o)))?a.kI():null)&&this.LD(a)},$Aa=function(a,b){a.C=b;
ZAa(a,b,g.Y(a.o),"hqdefault.jpg")},E5=function(a,b){if(!a.A){g.bG("a11y-announce",g.T("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title);
a.I=g.mG();a.A=new g.Zt((0,g.z)(a.cq,a,b),25);a.cq(b);var c=b||g.Y(a.o).experiments.l("autoplay_time")||1E4;a.o.ra("onAutonavCoundownStarted",c)}g.sq(a.element,"ytp-upnext-autoplay-paused")},G5=function(a){F5(a);
a.I=g.mG();a.cq();g.R(a.element,"ytp-upnext-autoplay-paused")},F5=function(a){a.A&&(a.A.dispose(),a.A=null)},H5=function(a,b){b=void 0===b?!1:b;
var c=g.Y(a.o);if(c.experiments.g("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.C.Wb(),a.Tm(),a.D=new window.Notification(g.T("YTP_PLAYLIST_UP_NEXT"),{body:d.title,icon:d.Zc(c)}),a.F=a.O(a.D,"click",a.nR),a.H.start())}F5(a);a.o.Dj(!1,b)},aBa=function(a){C5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.A=new g.V({G:"div",M:"ytp-subscribe-card",J:[{G:"img",M:"ytp-author-image",P:{src:b.profilePicture}},{G:"div",M:"ytp-subscribe-card-right",J:[{G:"div",M:"ytp-author-name",J:[b.author]},{G:"div",M:"html5-subscribe-button-container"}]}]});g.M(this,this.A);this.A.pa(this.element);this.B=new g.j_(g.T("YTP_SUBSCRIBE"),null,g.T("YTP_UNSUBSCRIBE"),null,!0,!1,b.Pl,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.B);this.B.pa(this.A.g["html5-subscribe-button-container"]);
this.hide()},I5=function(a){var b=g.Y(a),c=g.CI||g.ff?{style:"will-change: opacity"}:void 0,d=b.g,e=["ytp-videowall-still"];
b.l&&e.push("ytp-videowall-show-text");g.V.call(this,{G:"a",ba:e,P:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{G:"div",M:"ytp-videowall-still-image",P:{style:"{{background}}"}},{G:"span",M:"ytp-videowall-still-info",J:[{G:"span",M:"ytp-videowall-still-info-bg",J:[{G:"span",M:"ytp-videowall-still-info-content",P:c,J:[{G:"span",M:"ytp-videowall-still-info-title",J:["{{title}}"]},{G:"span",
M:"ytp-videowall-still-info-author",J:["{{author_and_views}}"]},{G:"span",M:"ytp-videowall-still-info-live",J:[g.T("YTP_LIVE")]},{G:"span",M:"ytp-videowall-still-info-duration",J:["{{duration}}"]}]}]}]},{G:"span",ba:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{G:"span",M:"ytp-videowall-still-listlabel-icon"},g.T("YTP_PLAYLIST"),{G:"span",M:"ytp-videowall-still-listlabel-length",J:[" (",{G:"span",J:["{{playlist_length}}"]},")"]}]},{G:"span",ba:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],J:[{G:"span",M:"ytp-videowall-still-listlabel-mix-icon"},g.T("YTP_MIX"),{G:"span",M:"ytp-videowall-still-listlabel-length",J:[" (50+)"]}]}]});this.B=d;this.o=a;this.A=null;this.U("click",this.C);this.U("keypress",this.F);this.O(a,"videodatachange",this.D);g.Y(a).N&&(a=a.app.da,b=this.element,g.Pa(a.g,b),g.Sa(a.g,b),c=String(a.F++),b.setAttribute("data-visual-id",c),g.af(this,(0,g.z)(a.D,a,b)))},J5=function(a){C5.call(this,a,"videowall-endscreen");
this.N=a;this.H=0;this.B=[];this.I=this.F=this.D=null;this.K=this.W=!1;this.C=new g.KF(this);g.M(this,this.C);this.L=new g.Zt(g.Ea(g.R,this.element,"ytp-show-tiles"),0);g.M(this,this.L);var b=new g.V({G:"button",ba:["ytp-button","ytp-endscreen-previous"],P:{"aria-label":g.T("YTP_PREVIOUS")},J:[g.tV()]});g.M(this,b);b.pa(this.element);b.U("click",this.kN,this);this.R=new g.rH({G:"div",M:"ytp-endscreen-content"});g.M(this,this.R);this.R.pa(this.element);b=new g.V({G:"button",ba:["ytp-button","ytp-endscreen-next"],
P:{"aria-label":g.T("YTP_NEXT")},J:[g.uV()]});g.M(this,b);b.pa(this.element);b.U("click",this.jN,this);this.A=new D5(a);g.M(this,this.A);g.aV(this.o,this.A.element,4);this.hide()},K5=function(a){return g.bV(a.o)&&a.pw()&&!a.I},bBa=function(a,b){return(0,g.G)(b.suggestions,function(b){b=g.jY(b);
g.M(a,b);return b})},L5=function(a){var b=a.it();
b!=a.W&&(a.W=b,a.o.T("autonavvisibility"))},M5=function(a){g.gV.call(this,a);
g.YG({YTP_AUTOPLAY_CANCEL:"Cancel autoplay",YTP_AUTOPLAY_NEXT:"Play next video",YTP_AUTOPLAY_PAUSED_3:"Autoplay is paused",YTP_CANCEL:"Cancel",YTP_MIX:"Mix",YTP_PLAYLIST_UP_NEXT:"Up Next",YTP_UNSUBSCRIBE:"Unsubscribe"});this.l=null;this.o=new g.KF(this);g.M(this,this.o);this.A=g.Y(a);cBa(a)?this.l=new J5(this.g):this.A.Z?this.l=new aBa(this.g):this.l=new C5(this.g);g.M(this,this.l);g.aV(this.g,this.l.element,4);this.zC();this.o.O(a,"videodatachange",this.zC,this);this.o.O(a,"crn_endscreen",this.jL,
this);this.o.O(a,"crx_endscreen",this.kL,this)},cBa=function(a){a=g.Y(a);
return a.Mc&&!a.Z};
g.p(C5,g.xH);C5.prototype.create=function(){this.created=!0};
C5.prototype.destroy=function(){this.created=!1};
C5.prototype.pw=function(){return!1};
C5.prototype.it=function(){return!1};g.p(D5,g.V);g.h=D5.prototype;g.h.Tm=function(){this.D&&(this.H.stop(),this.Aa(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.iB=function(){g.wH(this,g.DU(this.o))};
g.h.nR=function(){window.focus();this.Tm()};
g.h.hide=function(){g.V.prototype.hide.call(this)};
g.h.cq=function(a){a=a||g.Y(this.o).experiments.l("autoplay_time")||1E4;var b=Math.min(g.mG()-this.I,a);a=Math.min(b/a,1);this.K.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.o.Qa()?H5(this,!0):this.A&&this.A.start()};
g.h.xR=function(a){!g.Pd(this.B.element,g.yF(a))&&g.eX(a,this.o)&&H5(this)};
g.h.oP=function(){g.FU(this.o,!0)};
g.h.MQ=function(a){this.o.Qa();this.show();E5(this,a)};
g.h.LD=function(a){this.o.Qa();this.C&&this.C.Wb().videoId==a.Wb().videoId||$Aa(this,a)};
g.h.NQ=function(){this.o.Qa();F5(this);this.hide()};
g.h.V=function(){F5(this);this.Tm();g.V.prototype.V.call(this)};g.p(aBa,C5);g.p(I5,g.V);I5.prototype.Sj=function(){g.eV(this.o,this.element);var a=this.A.Wb().videoId,b=this.A.getPlaylistId();g.o0(this.o.app,a,this.A.Jd,b,void 0,void 0,void 0)};
I5.prototype.C=function(a){g.eX(a,this.o,this.B,this.A.Jd||void 0)&&this.Sj()};
I5.prototype.F=function(a){switch(a.keyCode){case 13:case 32:g.DF(a)||(this.Sj(),g.CF(a))}};
I5.prototype.D=function(){var a=this.o.getVideoData(),b=g.Y(this.o);this.B=a.isDni?!1:b.g};g.p(J5,C5);g.h=J5.prototype;g.h.create=function(){C5.prototype.create.call(this);var a=this.o.getVideoData();a&&(this.D=bBa(this,a),this.F=a);this.sg();this.C.O(this.o,"appresize",this.sg);this.C.O(this.o,"onVideoAreaChange",this.sg);this.C.O(this.o,"videodatachange",this.lN);this.C.O(this.o,"autonavchange",this.hA);this.C.O(this.o,"autonavcancel",this.iN);this.C.O(this.element,"transitionend",this.PS)};
g.h.destroy=function(){g.MF(this.C);g.cf(this.B);this.B=[];this.D=null;C5.prototype.destroy.call(this);g.sq(this.element,"ytp-show-tiles");this.L.stop()};
g.h.pw=function(){return 1!=this.F.autonavState};
g.h.show=function(){C5.prototype.show.call(this);g.sq(this.element,"ytp-show-tiles");g.Y(this.o).l?g.au(this.L):this.L.start();(this.K||this.I&&this.I!=this.F.clientPlaybackNonce)&&g.FU(this.o,!1);K5(this)?(L5(this),2==this.F.autonavState?g.Y(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.ji()?H5(this.A,!0):E5(this.A):3==this.F.autonavState&&G5(this.A)):(g.FU(this.o,!0),L5(this))};
g.h.hide=function(){C5.prototype.hide.call(this);G5(this.A);L5(this)};
g.h.PS=function(a){g.yF(a)==this.element&&this.sg()};
g.h.sg=function(){if(this.D&&this.D.length){g.R(this.element,"ytp-endscreen-paginate");var a=g.TU(this.N,!0),b=g.KH(this.N);b&&(b=b.pd()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.D.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,r=e/2,u=b<=f-2&&n>=r*m,C=e<=k-2&&n>=q*m;if((q+1)/r*d/c>c/(q/(r+1)*d)&&C)n-=q*m,e+=2;else if(u)n-=r*m,b+=2;else if(C)n-=q*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.bd(a.width/m||1,1,1.21);n*=g.bd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.R.element;g.Jh(a,m,n);g.rh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});$Aa(this.A,this.D[0]);g.S(this.element,"ytp-endscreen-takeover",K5(this));L5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&
2>f?0==k&&0==f&&(r=2):r=2),q=g.cd(q+this.H,l),0!=r){u=this.B[c];u||(u=new I5(this.o),this.B[c]=u,a.appendChild(u.element));C=Math.floor(n*k/e);var I=Math.floor(m*f/b),L=Math.floor(n*(k+r)/e)-C-4,X=Math.floor(m*(f+r)/b)-I-4;g.yh(u.element,I,C);g.Jh(u.element,X,L);g.rh(u.element,"transitionDelay",(k+f)/20+"s");g.S(u.element,"ytp-videowall-still-mini",1==r);g.S(u.element,"ytp-videowall-still-large",2<r);r=u;q=this.D[q];r.A!=q&&(r.A=q,ZAa(r,q,g.Y(r.o),g.qq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":
"mqdefault.jpg"),u=(q=q.Jd)&&q.itct)&&(q=r.o,g.Y(q).N&&(q=q.app.da,r=r.element,C=r.getAttribute("data-visual-id"),g.Pa(q.g,r),g.cV(q,"onLogServerVeCreated",{id:C,tracking_params:u})));c++}g.S(this.element,"ytp-endscreen-paginate",c<l);for(b=this.B.length-1;b>=c;b--)e=this.B[b],g.Jd(e.element),g.bf(e);this.B.length=c}};
g.h.lN=function(){var a=this.o.getVideoData();this.F!=a&&(this.H=0,this.D=bBa(this,a),this.F=a,this.sg())};
g.h.jN=function(){this.H+=this.B.length;this.sg()};
g.h.kN=function(){this.H-=this.B.length;this.sg()};
g.h.oK=function(){return!!this.A.A};
g.h.hA=function(a){1==a?(this.K=!1,this.I=this.F.clientPlaybackNonce,F5(this.A),this.l&&this.sg()):(this.K=!0,this.l&&K5(this)&&(2==a?E5(this.A):3==a&&G5(this.A)))};
g.h.iN=function(a){if(a){for(a=0;a<this.B.length;a++)g.fV(this.N,this.B[a].element,!0);this.hA(1)}else this.I=null,this.K=!1;this.sg()};
g.h.it=function(){return this.l&&K5(this)};g.p(M5,g.gV);g.h=M5.prototype;g.h.Hz=function(){var a=this.g.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!cBa(this.g)||b;a=g.FO(a,"ypc_module");var c=g.p0(this.g.app);return b&&!a&&!c};
g.h.Gz=function(){return this.l.it()};
g.h.kK=function(){return this.Gz()?this.l.oK():!1};
g.h.V=function(){g.ZU(this.g,"endscreen");g.gV.prototype.V.call(this)};
g.h.load=function(){g.gV.prototype.load.call(this);this.l.show();g.Y(this.g).Z&&.01>Math.random()&&g.Y(this.g).experiments.g("web_player_204_endscreen_logging_killswitch")&&g.QU(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.gV.prototype.unload.call(this);this.l.hide();this.l.destroy()};
g.h.jL=function(a){this.Hz()&&(this.l.created||this.l.create(),"load"==a.getId()&&this.load())};
g.h.kL=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.zC=function(){g.ZU(this.g,"endscreen");var a=Math.max(1E3*(this.g.getVideoData().lengthSeconds-10),0);a=new g.BQ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.M(this,a);var b=new g.BQ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.M(this,b);g.WU(this.g,[a,b])};g.ZX.endscreen=M5;})(_yt_player);
