(function(g){var window=this;var EBa=function(a,b){return g.Ub(a,b)},m6=function(a){g.Hm(a,"zx",g.wb());
return a},n6=function(a,b,c){g.ya(c)||(c=[String(c)]);
g.Km(a.g,b,c)},FBa=function(a,b){var c=[];
g.wk(b,function(a){try{var b=g.bD.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.aD(b)&&c.push(a):c.push(a)},a);
return c},GBa=function(a,b){var c=FBa(a,b);
(0,g.B)(c,function(a){g.bD.prototype.remove.call(this,a)},a)},HBa=function(a){if(a.xd){if(a.xd.locationOverrideToken)return{locationOverrideToken:a.xd.locationOverrideToken};
if(null!=a.xd.latitudeE7&&null!=a.xd.longitudeE7)return{latitudeE7:a.xd.latitudeE7,longitudeE7:a.xd.longitudeE7}}return null},IBa=function(a,b,c,d){var e=new g.ym(null,void 0);
a&&g.zm(e,a);b&&g.Am(e,b);c&&g.Bm(e,c);d&&g.Cm(e,d);return e},JBa=function(a){g.YF[a]&&(a=g.YF[a],(0,g.B)(a,function(a){g.WF[a]&&delete g.WF[a]}),a.length=0)},KBa=function(a){var b=g.VF();
if(b)if(b.clear(a),a)JBa(a);else for(var c in g.YF)JBa(c)},o6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.sm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",LBa(this,a.capabilities||""),MBa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},LBa=function(a,b){a.capabilities.clear();
(0,g.Kd)(b.split(","),g.Ea(EBa,NBa)).forEach(function(b){a.capabilities.add(b)})},MBa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},p6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},q6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},OBa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},PBa=function(a){return new p6(a)},QBa=function(a){return g.ya(a)?(0,g.G)(a,PBa):[]},r6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},s6=function(a){return g.ya(a)?"["+(0,g.G)(a,r6).join(",")+"]":"null"},t6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},RBa=function(a){return(0,g.G)(a,function(a){return{key:a.id,
name:a.name}})},u6=function(a,b){return g.La(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},v6=function(a,b){return g.La(a,function(a){return q6(a,b)})},SBa=function(){var a=(0,g.RG)();
a&&GBa(a,a.g.Nd(!0))},w6=function(){var a=g.UG("yt-remote-connected-devices")||[];
g.gb(a);return a},TBa=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(a,b){return 0==b?a:a.substring(c.length)})},UBa=function(a){g.TG("yt-remote-connected-devices",a,86400)},y6=function(){if(x6)return x6;
var a=g.UG("yt-remote-device-id");a||(a=t6(),g.TG("yt-remote-device-id",a,31536E3));for(var b=w6(),c=1,d=a;g.Pa(b,d);)c++,d=a+"#"+c;return x6=d},z6=function(){var a=w6(),b=y6();
g.Pa(a,b);g.WG()&&g.jb(a,b);a=TBa(a);if(g.Qa(a))try{g.EG("remote_sid")}catch(c){}else try{g.DG("remote_sid",a.join(","),-1)}catch(c){}},VBa=function(){return g.UG("yt-remote-session-browser-channel")},WBa=function(){return g.UG("yt-remote-local-screens")||[]},XBa=function(){g.TG("yt-remote-lounge-token-expiration",!0,86400)},YBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(WBa(),function(a){return a.loungeToken}),c=(0,g.G)(a,function(a){return a.loungeToken});
(0,g.em)(c,function(a){return!g.Pa(b,a)})&&XBa();
g.TG("yt-remote-local-screens",a,31536E3)},ZBa=function(a,b){g.TG("yt-remote-session-browser-channel",a);
g.TG("yt-remote-session-screen-id",b);var c=w6(),d=y6();g.Pa(c,d)||c.push(d);UBa(c);z6()},A6=function(a){a||(g.VG("yt-remote-session-screen-id"),g.VG("yt-remote-session-video-id"));
z6();a=w6();g.Ua(a,y6());UBa(a)},$Ba=function(){if(!B6){var a=g.mD();
a&&(B6=new g.WC(a))}return B6?!!B6.get("yt-remote-use-staging-server"):!1},aCa=function(){var a=window.document.createElement("a");
g.Yc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ab(a)},bCa=function(a,b){var c=g.Dd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.$c(c,g.ce("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},cCa=function(){var a=aCa(),b=window.document.getElementById(a),c=b&&g.gF(b,"loaded");
c||b&&!c||(b=bCa(a,function(){g.gF(b,"loaded")||(g.fF(b,"loaded","true"),g.bG(a),g.VD(g.Ea(KBa,a),0))}))},C6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},dCa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},D6=function(a){a.length?eCa(a.shift(),function(){D6(a)}):E6()},fCa=function(a){return"chrome-extension://"+a+F6},eCa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},G6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},E6=function(){var a=dCa();
a&&a(!1,"No cast extension found")},H6=function(){if(gCa){var a=2,b=dCa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;eCa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",E6,c)}},hCa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(H6(),a({command:"cast.sender.init"}))},iCa=function(){H6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);D6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+F6,"//www.gstatic.com/eureka/clank"+F6])},I6=function(a,b,c){g.K.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.cd=b;this.B=(0,g.z)(this.pI,this);this.g=!1;this.l=0;this.o=this.va=null;this.A=[]},J6=function(){},K6=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.Om(this);this.l=new g.tg;this.l.setInterval(250)},kCa=function(a,b,c){a.ij=1;
a.Ug=m6(b.clone());a.pi=c;a.C=!0;jCa(a,null)},L6=function(a,b,c,d,e){a.ij=1;
a.Ug=m6(b.clone());a.pi=null;a.C=c;e&&(a.IC=!1);jCa(a,d)},jCa=function(a,b){a.Qj=(0,g.F)();
M6(a);a.rh=a.Ug.clone();n6(a.rh,"t",a.D);a.Tl=0;a.Oc=a.g.Gq(a.g.Ml()?b:null);0<a.mr&&(a.Lo=new g.Wk((0,g.z)(a.UD,a,a.Oc),a.mr));a.A.U(a.Oc,"readystatechange",a.LT);var c=a.Sh?g.bc(a.Sh):{};a.pi?(a.Ap="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Oc.send(a.rh,a.Ap,a.pi,c)):(a.Ap="GET",a.IC&&!g.zd&&(c.Connection="close"),a.Oc.send(a.rh,a.Ap,null,c));a.g.mf(1)},nCa=function(a,b,c){for(var d=!0;!a.Eh&&a.Tl<c.length;){var e=lCa(a,c);
if(e==N6){4==b&&(a.Vg=4,O6(15),d=!1);break}else if(e==mCa){a.Vg=4;O6(16);d=!1;break}else P6(a,e)}4==b&&0==c.length&&(a.Vg=1,O6(17),d=!1);a.tf=a.tf&&d;d||(Q6(a),R6(a))},lCa=function(a,b){var c=a.Tl,d=b.indexOf("\n",c);
if(-1==d)return N6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return mCa;d+=1;if(d+c>b.length)return N6;var e=b.substr(d,c);a.Tl=d+c;return e},pCa=function(a,b){a.Qj=(0,g.F)();
M6(a);var c=b?window.location.hostname:"";a.rh=a.Ug.clone();g.Hm(a.rh,"DOMAIN",c);g.Hm(a.rh,"t",a.D);try{a.uf=new window.ActiveXObject("htmlfile")}catch(n){Q6(a);a.Vg=7;O6(22);R6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in S6)k=S6[l];else if(l in oCa)k=S6[l]=oCa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=S6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.ad(g.wc("b/12014412"),d);a.uf.open();a.uf.write(g.Sc(c));a.uf.close();a.uf.parentWindow.m=(0,g.z)(a.SS,a);a.uf.parentWindow.d=(0,g.z)(a.VB,a,!0);a.uf.parentWindow.rpcClose=(0,g.z)(a.VB,a,!1);c=a.uf.createElement("DIV");a.uf.parentWindow.document.body.appendChild(c);d=g.Jc(a.rh.toString());d=g.qb(g.Gc(d));d=g.ad(g.wc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Sc(d);
a.g.mf(1)},M6=function(a){a.Ru=(0,g.F)()+a.B;
qCa(a,a.B)},qCa=function(a,b){if(null!=a.ik)throw Error("WatchDog timer not null");
a.ik=T6((0,g.z)(a.jT,a),b)},U6=function(a){a.ik&&(g.w.clearTimeout(a.ik),a.ik=null)},R6=function(a){a.g.Xx()||a.Eh||a.g.yo(a)},Q6=function(a){U6(a);
g.bf(a.Lo);a.Lo=null;a.l.stop();g.Um(a.A);if(a.Oc){var b=a.Oc;a.Oc=null;b.abort();b.dispose()}a.uf&&(a.uf=null)},P6=function(a,b){try{a.g.OB(a,b),a.g.mf(4)}catch(c){}},sCa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;rCa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){sCa(a,b,c,d,f)},f)})}},rCa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{V6(d),c(!0)}catch(e){}};
d.onerror=function(){try{V6(d),c(!1)}catch(e){}};
d.onabort=function(){try{V6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{V6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},V6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},tCa=function(a){this.g=a;
this.l=new J6},uCa=function(a){var b=W6(a.g,a.pk,"/mail/images/cleardot.gif");
m6(b);sCa(b.toString(),5E3,(0,g.z)(a.BH,a),3,2E3);a.mf(1)},Y6=function(a){var b=a.g.H;
if(null!=b)O6(5),b?(O6(11),X6(a.g,a,!1)):(O6(12),X6(a.g,a,!0));else if(a.ne=new K6(a,void 0,void 0,void 0),a.ne.Sh=a.kr,b=a.g,b=W6(b,b.Ml()?a.Ok:null,a.lr),O6(5),!g.xd||g.sc(10))n6(b,"TYPE","xmlhttp"),L6(a.ne,b,!1,a.Ok,!1);else{n6(b,"TYPE","html");var c=a.ne;a=!!a.Ok;c.ij=3;c.Ug=m6(b.clone());pCa(c,a)}},Z6=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new J6;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},vCa=function(a,b){this.g=a;
this.map=b;this.context=null},wCa=function(a){g.df.call(this,"statevent",a)},xCa=function(a,b){g.df.call(this,"timingevent",a);
this.size=b},yCa=function(a){g.df.call(this,"serverreachability",a)},BCa=function(a){zCa(a);
if(3==a.g){var b=a.yl++,c=a.un.clone();g.Hm(c,"SID",a.o);g.Hm(c,"RID",b);g.Hm(c,"TYPE","terminate");$6(a,c);b=new K6(a,a.o,b,void 0);b.ij=2;b.Ug=m6(c.clone());(new window.Image).src=b.Ug;b.Qj=(0,g.F)();M6(b)}ACa(a)},CCa=function(a){a.WH(1,0);
a.un=W6(a,null,a.jr);a7(a)},zCa=function(a){a.Kg&&(a.Kg.abort(),a.Kg=null);
a.sc&&(a.sc.cancel(),a.sc=null);a.jg&&(g.w.clearTimeout(a.jg),a.jg=null);b7(a);a.Sd&&(a.Sd.cancel(),a.Sd=null);a.Mg&&(g.w.clearTimeout(a.Mg),a.Mg=null)},DCa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new vCa(a.HO++,b));2!=a.g&&3!=a.g||a7(a)},a7=function(a){a.Sd||a.Mg||(a.Mg=T6((0,g.z)(a.TB,a),0),a.Wi=0)},FCa=function(a,b){if(1==a.g){if(!b){a.yl=Math.floor(1E5*Math.random());
var c=a.yl++,d=new K6(a,"",c,void 0);d.Sh=null;var e=c7(a),f=a.un.clone();g.Hm(f,"RID",c);g.Hm(f,"CVER","1");$6(a,f);kCa(d,f,e);a.Sd=d;a.g=2}}else 3==a.g&&(b?ECa(a,b):0==a.l.length||a.Sd||ECa(a))},ECa=function(a,b){if(b)if(6<a.Gh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.yl-1;var d=c7(a)}else c=b.F,d=b.pi;else c=a.yl++,d=c7(a);var e=a.un.clone();g.Hm(e,"SID",a.o);g.Hm(e,"RID",c);g.Hm(e,"AID",a.xj);$6(a,e);c=new K6(a,a.o,c,a.Wi+1);c.Sh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Sd=c;kCa(c,e,d)},$6=function(a,b){if(a.od){var c=a.od.Fx();
c&&g.Jb(c,function(a,c){g.Hm(b,c,a)})}},c7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Gh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Gh?e:f-d;try{g.Jb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},GCa=function(a){a.sc||a.jg||(a.D=1,a.jg=T6((0,g.z)(a.SB,a),0),a.Ji=0)},d7=function(a){if(a.sc||a.jg||3<=a.Ji)return!1;
a.D++;a.jg=T6((0,g.z)(a.SB,a),HCa(a,a.Ji));a.Ji++;return!0},X6=function(a,b,c){a.zp=c;
a.Ff=b.og;a.C||CCa(a)},b7=function(a){null!=a.Ih&&(g.w.clearTimeout(a.Ih),a.Ih=null)},HCa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},e7=function(a,b){if(2==b||9==b){var c=null;
a.od&&(c=null);var d=(0,g.z)(a.GU,a);c||(c=new g.ym("//www.google.com/images/cleardot.gif"),m6(c));rCa(c.toString(),1E4,d)}else O6(2);ICa(a,b)},ICa=function(a,b){a.g=0;
a.od&&a.od.Aw(b);ACa(a);zCa(a)},ACa=function(a){a.g=0;
a.Ff=-1;if(a.od)if(0==a.A.length&&0==a.l.length)a.od.tq();else{g.Xa(a.A);var b=g.Xa(a.l);a.A.length=0;a.l.length=0;a.od.tq(b)}},W6=function(a,b,c){var d=g.Im(c);
if(""!=d.l)b&&g.Am(d,b+"."+d.l),g.Bm(d,d.B);else{var e=window.location;d=IBa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Ak&&g.Jb(a.Ak,function(a,b){g.Hm(d,b,a)});
g.Hm(d,"VER",a.Gh);$6(a,d);return d},T6=function(a,b){if(!g.Aa(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},O6=function(a){f7.dispatchEvent(new wCa(f7,a))},JCa=function(){},KCa=function(a,b){this.action=a;
this.params=b||{}},g7=function(a,b){g.K.call(this);
this.g=new g.Zt(this.JS,0,this);g.M(this,this.g);this.cd=5E3;this.l=0;if(g.Aa(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Aa(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},h7=function(a,b,c){this.K=a;
this.C=b;this.o=new g.VC;this.l=new g7(this.nV,this);this.g=this.Ua=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.L=c||!1},LCa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.zp,sessionId:a.g.o,arrayId:a.g.xj}},MCa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&FCa(a.g),BCa(a.g));a.F=0},i7=function(a){return!!a.g&&3==a.g.g},NCa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},j7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Jg(a)||"";b&&(this.port=":"+b);this.domain=g.Ig(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.zb(a,"10.0")&&(this.l=!1))},k7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Tg(c+b,{})},l7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ea(a.A,d,!0),onError:g.Ea(a.o,e),td:g.Ea(a.B,e)};c&&(a.Jb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.kE(b,a)},RCa=function(){var a=OCa;
PCa();m7.push(a);QCa(m7)},n7=function(a,b){PCa();
var c=m7,d=SCa(a,String(b));g.Qa(c)?TCa(d):(QCa(c),(0,g.B)(c,function(a){a(d)}))},PCa=function(){m7||(m7=g.x("yt.mdx.remote.debug.handlers_")||[],g.va("yt.mdx.remote.debug.handlers_",m7,void 0))},TCa=function(a){var b=(o7+1)%50;
o7=b;p7[b]=a;q7||(q7=49==b)},QCa=function(a){var b=p7;
if(b[0]){var c=o7,d=q7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
p7=Array(50);o7=-1;q7=!1}},SCa=function(a,b){var c=((0,g.F)()-UCa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},r7=function(a){g.NF.call(this);
this.D=a;this.g=[]},VCa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},WCa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Kd)(a.g,function(a){return!!u6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=VCa(a,b[d])||c;return c},XCa=function(a,b){var c=a.g.length;
a.g=(0,g.Kd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},s7=function(a,b,c,d){g.NF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.va=window.NaN},u7=function(a){r7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;t7(this);this.info("Initializing with "+s6(this.g))},YCa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(a){return a.id}),c=k7(a.o,"/pairing/get_lounge_token_batch");
l7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.CI,a),(0,g.z)(a.BI,a))}},t7=function(a){var b=QBa(WBa());
b=(0,g.Kd)(b,function(a){return!a.uuid});
return WCa(a,b)},v7=function(a,b){YBa((0,g.G)(a.g,OBa));
b&&XBa()},x7=function(a,b){g.NF.call(this);
this.C=b;var c=g.UG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Pa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;w7("Initialized with "+g.Ag(this.g))},ZCa=function(a,b,c){var d=k7(a.B,"/pairing/get_screen_availability");
l7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},y7=function(a,b){a:if(g.Ob(b)!=g.Ob(a.g))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(w7("Updated online screens: "+g.Ag(a.g)),a.g=b,a.T("screenChange"));$Ca(a)},z7=function(a){(0,window.isNaN)(a.o)||g.XD(a.o);
a.o=g.VD((0,g.z)(a.hu,a),0<a.A&&a.A<(0,g.F)()?2E4:1E4)},w7=function(a){n7("OnlineScreenService",a)},aDa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.bc("Requesting availability of screen w/o lounge token.")});
return b},$Ca=function(a){a=g.Qb(g.Kb(a.g,function(a){return a}));
g.gb(a);a.length?g.TG("yt-remote-online-screen-ids",a.join(","),60):g.VG("yt-remote-online-screen-ids")},A7=function(a){r7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};bDa(this)},dDa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ge();if(k=(c?v6(k,c):null)||v6(k,b)){k.uuid=b;var l=B7(a,k);ZCa(a.l,l,function(a){e(a?l:null)})}else c?cDa(a,c,(0,g.z)(function(a){var f=B7(this,new p6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));ZCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},eDa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},cDa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Jb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.kE(k7(a.C,"/pairing/get_lounge_token_batch"),e)},fDa=function(a){a.g=a.o.ge();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+s6(a.g))},bDa=function(a){C7(a);
a.o=new u7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.SI,a));fDa(a);a.A=QBa(g.UG("yt-remote-automatic-screen-cache")||[]);C7(a);a.info("Initializing automatic screens: "+s6(a.A));a.l=new x7(a.C,(0,g.z)(a.ge,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.T("onlineScreenChange")},a))},B7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=v6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.TG("yt-remote-automatic-screen-cache",(0,g.G)(a.A,OBa)));C7(a);a.B[b.uuid]=b.id;g.TG("yt-remote-device-id-map",a.B,31536E3);return b},C7=function(a){a.B=g.UG("yt-remote-device-id-map")||{}},D7=function(a,b,c){g.NF.call(this);
this.L=c;this.H=a;this.l=b;this.o=null},E7=function(a,b){n7(a.L,b)},F7=function(a,b){D7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.tV,this);this.B=(0,g.z)(this.vT,this);this.A=g.VD((0,g.z)(function(){gDa(this,null)},this),12E4)},hDa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ag(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){E7(this,"Failed to send message: getMdxSessionStatus.")},a)):E7(a,"Sending yt message without session: "+g.Ag(b))},gDa=function(a,b){g.XD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.zo,a),d=(0,g.z)(a.ke,a);a.Qx(b,c,d,5)}}else a.ke(Error("Waiting for session status timed out."))},G7=function(a,b,c){D7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.wV,this);this.g=g.y},iDa=function(a){a.g=a.H.bE(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.zo(a)},a),(0,g.z)(function(a){this.g=g.y;
this.ke(a)},a))},jDa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}$Ba()&&(b.env_useStageMdx=1);return g.Rg(b)},H7=function(a,b){D7.call(this,a,b,"ManualSession");
this.g=g.VD((0,g.z)(this.zj,this,null),150)},I7=function(a,b,c,d){g.NF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.VR,this)},kDa=function(a,b){return b?g.La(a.o,function(a){return q6(b,a.label)},a):null},J7=function(a){n7("Controller",a)},OCa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},K7=function(a){return a.B||!!a.o.length||!!a.g},L7=function(a,b,c){b!=a.g&&(g.bf(a.g),(a.g=b)?(c?a.T("yt-remote-cast2-receiver-resumed",b.l):a.T("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.QB,a,b)),b.o?a.T("yt-remote-cast2-session-change",b.o):c&&a.g.zj(null)):a.T("yt-remote-cast2-session-change",null))},lDa=function(a){var b=a.l.aE(),c=a.g&&a.g.l;
a=(0,g.G)(b,function(a){c&&q6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=kDa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},rDa=function(a,b,c,d,e,f,k){mDa()?nDa(b,e,f,k)&&(N7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?oDa(a,c):(window.__onGCastApiAvailable=function(b,d){b?oDa(a,c):(O7("Failed to load cast API: "+d),P7(!1),N7(!1),g.VG("yt-remote-cast-available"),g.VG("yt-remote-cast-receiver"),pDa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):cCa():G6("CriOS")?hCa():G6("Android")&&G6("Chrome/")&&window.navigator.presentation?iCa():window.chrome&&window.navigator.presentation&&!G6("Edge")?(H6(),D6(qDa.map(fCa))):E6())):M7("Cannot initialize because not running Chrome")},pDa=function(){M7("dispose");
var a=Q7();a&&a.dispose();g.va("yt.mdx.remote.cloudview.instance_",null,void 0);sDa(!1);g.$F(R7);R7.length=0},S7=function(){return!!g.UG("yt-remote-cast-installed")},tDa=function(){var a=g.UG("yt-remote-cast-receiver");
return a?a.friendlyName:null},uDa=function(){M7("clearCurrentReceiver");
g.VG("yt-remote-cast-receiver")},vDa=function(){return S7()?Q7()?Q7().getCastSession():(O7("getCastSelector: Cast is not initialized."),null):(O7("getCastSelector: Cast API is not installed!"),null)},U7=function(){S7()?Q7()?T7()?(M7("Requesting cast selector."),Q7().requestSession()):(M7("Wait for cast API to be ready to request the session."),R7.push(g.ZF("yt-remote-cast2-api-ready",U7))):O7("requestCastSelector: Cast is not initialized."):O7("requestCastSelector: Cast API is not installed!")},V7=
function(a,b){T7()?Q7().setConnectedScreenStatus(a,b):O7("setConnectedScreenStatus called before ready.")},mDa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.CI||a},wDa=function(a,b){Q7().init(a,b)},nDa=function(a,b,c,d){var e=!1;
Q7()||(a=new I7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.TG("yt-remote-cast-available",a);g.cG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){M7("onReceiverSelected: "+a.friendlyName);
g.TG("yt-remote-cast-receiver",a);g.cG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){M7("onReceiverResumed: "+a.friendlyName);
g.TG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){M7("onSessionChange: "+r6(a));
a||g.VG("yt-remote-cast-receiver");g.cG("yt-remote-cast2-session-change",a)}),g.va("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
M7("cloudview.createSingleton_: "+e);return e},Q7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},oDa=function(a,b){P7(!0);
N7(!1);wDa(a,function(a){a?(sDa(!0),g.bG("yt-remote-cast2-api-ready")):(O7("Failed to initialize cast API."),P7(!1),g.VG("yt-remote-cast-available"),g.VG("yt-remote-cast-receiver"),pDa());b(a)})},M7=function(a){n7("cloudview",a)},O7=function(a){n7("cloudview",a)},P7=function(a){M7("setCastInstalled_ "+a);
g.TG("yt-remote-cast-installed",a)},T7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},sDa=function(a){M7("setApiReady_ "+a);
g.va("yt.mdx.remote.cloudview.apiReady_",a,void 0)},N7=function(a){g.va("yt.mdx.remote.cloudview.initializing_",a,void 0)},W7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.If=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},X7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.If=!1;a.hasNext=!1;a.F=0;a.D=(0,g.F)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},Y7=function(a){return a.gb()?((0,g.F)()-a.D)/1E3:0},Z7=function(a,b){a.F=b;
a.D=(0,g.F)()},$7=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},a8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&X7(a)},b8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.l);b.hasPrevious=a.If;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},d8=function(a,b){g.NF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.lC;this.o=this.l=null;this.H=(0,g.z)(this.rP,this);this.D=(0,g.z)(this.Bl,this);this.F=(0,g.z)(this.qP,this);this.I=(0,g.z)(this.DP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Xu,this),xDa(this))):c=3;0!=c&&(b?this.Xu(c):g.VD((0,g.z)(function(){this.Xu(c)},this),0));
var d=vDa();d&&c8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},e8=function(a){return new W7(a.A.getPlayerContextData())},xDa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ea(this.QR,a),this))},a)},yDa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},f8=function(a,b){50>a.B.Ac()&&g.nC(a.B,b)},h8=function(a,b,c){var d=e8(a);
Z7(d,c);-1E3!=d.g&&(d.g=b);g8(a,d)},i8=function(a,b,c){a.A.sendMessage(b,c)},g8=function(a,b){yDa(a);
a.A.setPlayerContextData(b8(b));xDa(a)},c8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.Bl(null));
a.o=b;a.o&&(n7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.Bl(a.o.media[0]))},zDa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=e8(a);b.contentId!=d.videoId&&n7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;Z7(d,a.l.getEstimatedTime());g8(a,d)}else n7("CP","No cast media video. Ignoring state update.")},j8=function(a,b,c){return(0,g.z)(function(a){this.bc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.bc("Retrying "+b+" using MDx browser channel."),i8(this,b,c))},a)},k8=function(a,b,c){g.NF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.L=window.NaN;this.R=[];this.A=this.D=this.o=this.Va=this.g=null;this.na=a;this.R.push(g.wF(window,"beforeunload",(0,g.z)(this.tI,this)));this.l=[];this.Va=new W7;this.Y=b.id;this.g=ADa(this,c);this.g.subscribe("handlerOpened",this.vP,this);this.g.subscribe("handlerClosed",this.sP,this);this.g.subscribe("handlerError",this.tP,this);this.g.subscribe("handlerMessage",this.uP,this);NCa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Va.videoId;g.WG()&&g.TG("yt-remote-session-video-id",a)},this)},l8=function(a){n7("conn",a)},ADa=function(a,b){return new h7(k7(a.na,"/bc"),b)},m8=function(a,b){a.T("proxyStateChange",b)},BDa=function(a){a.B=g.VD((0,g.z)(function(){l8("Connecting timeout");
this.C(1)},a),2E4)},n8=function(a){g.XD(a.B);
a.B=window.NaN},o8=function(a){g.XD(a.L);
a.L=window.NaN},CDa=function(a){p8(a);
a.K=g.VD((0,g.z)(function(){q8(this,"getNowPlaying")},a),2E4)},p8=function(a){g.XD(a.K);
a.K=window.NaN},EDa=function(a,b){b&&(n8(a),o8(a));
b==(i7(a.g)&&(0,window.isNaN)(a.B))?b&&(m8(a,1),q8(a,"getSubtitlesTrack")):b?(a.W()&&a.Va.reset(),m8(a,1),q8(a,"getNowPlaying"),DDa(a)):a.C(1)},FDa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Va.videoId&&(g.Xb(b.params)?a.Va.l=null:a.Va.l=b.params,a.T("remotePlayerChange"))},GDa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Va.listId=b.params.listId||a.Va.listId;a8(a.Va,c,d);a.T("remoteQueueChange")},IDa=function(a,b){b.params=b.params||{};
GDa(a,b);HDa(a,b);a.T("autoplayDismissed")},HDa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
Z7(a.Va,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Va.g&&(c=-1E3);a.Va.g=c;c=Number(b.params.loadedTime);a.Va.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Va.H=(0,window.isNaN)(c)?0:c;c=a.Va;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Va;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Va.g?CDa(a):p8(a);
a.T("remotePlayerChange")},JDa=function(a,b){if(-1E3!=a.Va.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Va.g=c;c=(0,window.parseInt)(b.params.currentTime,10);Z7(a.Va,(0,window.isNaN)(c)?0:c);a.T("remotePlayerChange")}},KDa=function(a,b){var c="true"==b.params.muted;
a.Va.volume=(0,window.parseInt)(b.params.volume,10);a.Va.muted=c;a.T("remotePlayerChange")},LDa=function(a,b){a.D=b.params.videoId;
a.T("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},MDa=function(a,b){var c="true"==b.params.hasNext;
a.Va.If="true"==b.params.hasPrevious;a.Va.hasNext=c;a.T("previousNextChange")},DDa=function(a){g.XD(a.I);
a.I=g.VD((0,g.z)(a.C,a,1),864E5)},q8=function(a,b,c){c?l8("Sending: action="+b+", params="+g.Ag(c)):l8("Sending: action="+b);
a.g.sendMessage(b,c)},r8=function(a){r7.call(this,"ScreenServiceProxy");
this.bd=a;this.l=[];this.l.push(this.bd.$_s("screenChange",(0,g.z)(this.rV,this)));this.l.push(this.bd.$_s("onlineScreenChange",(0,g.z)(this.qR,this)))},RDa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.PD("MDX_CONFIG")||b;SBa();z6();s8||(s8=new j7(b?b.loungeApiHost:void 0),$Ba()&&(s8.g="/api/loungedev"));t8||(t8=g.x("yt.mdx.remote.deferredProxies_")||[],g.va("yt.mdx.remote.deferredProxies_",t8,void 0));NDa();var c=u8();if(!c){var d=new A7(s8);g.va("yt.mdx.remote.screenService_",d,void 0);c=u8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);rDa(a,d,function(a){a?v8()&&V7(v8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.cG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.va("yt.mdx.remote.initialized_",!0,void 0),w8("Initializing: "+g.Ag(b)),x8.push(g.ZF("yt-remote-cast2-availability-change",function(){g.cG("yt-remote-receiver-availability-change")})),x8.push(g.ZF("yt-remote-cast2-receiver-selected",function(){y8(null);
g.cG("yt-remote-auto-connect","cast-selector-receiver")})),x8.push(g.ZF("yt-remote-cast2-receiver-resumed",function(){g.cG("yt-remote-receiver-resumed","cast-selector-receiver")})),x8.push(g.ZF("yt-remote-cast2-session-change",ODa)),x8.push(g.ZF("yt-remote-connection-change",function(a){a?V7(v8(),"YouTube TV"):z8()||(V7(null,null),uDa())})),a=A8(),b.isAuto&&(a.id+="#dial"),g.TF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),w8(" -- with channel params: "+
g.Ag(a)),PDa(a),c.start(),v8()||QDa())},TDa=function(){var a=SDa();
S7()&&g.UG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},SDa=function(){var a=u8().bd.$_gos();
var b=B8();b&&C8()&&(u6(a,b)||a.push(b));return RBa(a)},D8=function(){var a=UDa();
!a&&S7()&&tDa()&&(a={key:"cast-selector-receiver",name:tDa()});return a},UDa=function(){var a=SDa(),b=B8();
b||(b=z8());return g.La(a,function(a){return b&&q6(b,a.key)?!0:!1})},B8=function(){var a=v8();
if(!a)return null;var b=u8().ge();return v6(b,a)},ODa=function(a){w8("remote.onCastSessionChange_: "+r6(a));
if(a){var b=B8();b&&b.id==a.id?V7(b.id,"YouTube TV"):(b&&E8(),F8(a,1))}else C8()&&E8()},E8=function(){T7()?Q7().stopSession():O7("stopSession called before API ready.");
var a=C8();a&&(a.disconnect(1),G8(null))},H8=function(){var a=C8();
return!!a&&3!=a.getProxyState()},w8=function(a){n7("remote",a)},u8=function(){if(!I8){var a=g.x("yt.mdx.remote.screenService_");
I8=a?new r8(a):null}return I8},v8=function(){return g.x("yt.mdx.remote.currentScreenId_")},VDa=function(a){g.va("yt.mdx.remote.currentScreenId_",a,void 0)},WDa=function(){return g.x("yt.mdx.remote.connectData_")},y8=function(a){g.va("yt.mdx.remote.connectData_",a,void 0)},C8=function(){return g.x("yt.mdx.remote.connection_")},G8=function(a){var b=C8();
y8(null);a||VDa("");g.va("yt.mdx.remote.connection_",a,void 0);t8&&((0,g.B)(t8,function(b){b(a)}),t8.length=0);
b&&!a?g.cG("yt-remote-connection-change",!1):!b&&a&&g.cG("yt-remote-connection-change",!0)},z8=function(){var a=g.WG();
if(!a)return null;var b=u8().ge();return v6(b,a)},F8=function(a,b){B8()&&B8();
VDa(a.id);var c=new k8(s8,a,A8());c.connect(b,WDa());c.subscribe("beforeDisconnect",function(a){g.cG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){C8()&&G8(null)});
G8(c)},QDa=function(){var a=z8();
a?(w8("Resume connection to: "+r6(a)),F8(a,0)):(A6(),uDa(),w8("Skipping connecting because no session screen found."))},NDa=function(){var a=A8();
if(g.Xb(a)){a=y6();var b=g.UG("yt-remote-session-name")||"",c=g.UG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.va("yt.mdx.remote.channelParams_",a,void 0)}},A8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},PDa=function(a){a?(g.TG("yt-remote-session-app",a.app),g.TG("yt-remote-session-name",a.name)):(g.VG("yt-remote-session-app"),g.VG("yt-remote-session-name"));
g.va("yt.mdx.remote.channelParams_",a,void 0)},J8=function(a,b,c){g.K.call(this);
this.F=a;this.l=b;this.o=new g.KF(this);g.M(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.JQ);this.o.O(b,"captionschanged",this.pP);this.o.O(b,"captionssettingschanged",this.pD);this.o.O(b,"videoplayerreset",this.Ao);this.o.O(b,"mdxautoplaycancel",this.AH);this.R=this.o.O(b,"onVolumeChange",this.AB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.NB,this);c.subscribe("remotePlayerChange",this.El,this);c.subscribe("remoteQueueChange",this.Ao,this);c.subscribe("autoplayUpNext",this.kB,
this);c.subscribe("previousNextChange",this.KB,this);c.subscribe("nowAutoplaying",this.CB,this);c.subscribe("autoplayDismissed",this.jB,this);this.suggestion=null;this.H=new g.tP(64);this.A=new g.Zt(this.lD,500,this);g.M(this,this.A);this.B=new g.Zt(this.mD,1E3,this);g.M(this,this.B);this.K=new I6(this.UU,0,this);g.M(this,this.K);this.C={};this.L=new g.Zt(this.MD,1E3,this);g.M(this,this.L);this.I=new g.Wk(this.pN,1E3,this);g.M(this,this.I);this.N=g.y;this.pD();this.Ao();this.El()},K8=function(a,b){var c=
a.F,d=a.l.getVideoData().lengthSeconds;
c.H=b||0;c.g.T("progresssync",b,d)},XDa=function(a){K8(a,0);
a.A.stop();L8(a,new g.tP(64))},N8=function(a,b){if(M8(a)&&!a.D){var c=null;
b&&(c={style:a.l.ii()},g.ec(c,b));a.g.bD(a.l.getVideoData(1).videoId,c);a.C=e8(a.g).l}},O8=function(a,b){var c=a.l.Sf();
if(c){var d=c.de();var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.sj;f=HBa(f);var n=e8(c);l=l||0;var q={videoId:k,currentIndex:l};a8(n,k,l);g.t(b)&&(Z7(n,b),q.currentTime=b);g.t(e)&&(q.listId=e);null!=d&&(q.playerParams=d);null!=m&&(q.clickTrackingParams=m);null!=f&&(q.locationInfo=g.Ag(f));i8(c,"setPlaylist",q);e||g8(c,n);L8(a,new g.tP(1))},YDa=function(a,b){if(b){var c=a.l.uc("captions","tracklist",{My:1});
c&&c.length?(a.l.Id("captions","track",b),a.D=!1):(a.l.Cj("captions"),a.D=!0)}else a.l.Id("captions","track",{})},M8=function(a){return e8(a.g).videoId==a.l.getVideoData(1).videoId},L8=function(a,b){a.B.stop();
var c=a.H;if(!g.BP(c,b)){var d=g.W(b,2);d!=g.W(a.H,2)&&g.MU(a.l,d);a.H=b;ZDa(a.F,c,b)}},P8=function(a){g.V.call(this,{G:"div",
M:"ytp-remote",J:[{G:"div",M:"ytp-remote-display-status",J:[{G:"div",M:"ytp-remote-display-status-icon",J:[g.kpa()]},{G:"div",M:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.o=new g.zV(this,250);g.M(this,this.o);this.A=a;this.O(a,"presentingplayerstatechange",this.B);$Da(this,g.JU(a))},$Da=function(a,b){if(3==a.A.Qa()){var c={RECEIVER_NAME:a.A.uc("remote","currentReceiver").name};
c=g.W(b,128)?g.T("YTP_MDX_STATUS_ERROR_2",c):b.gb()||g.W(b,4)?g.T("YTP_MDX_STATUS_PLAYING_2",c):g.T("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},Q8=function(a,b){g.KZ.call(this,g.T("YTP_MDX_TITLE"),0,a,b);
this.o=a;this.H={};this.O(a,"onMdxReceiversChange",this.K);this.O(a,"presentingplayerstatechange",this.K);this.K()},R8=function(a){g.gV.call(this,a);
g.YG({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:t6(),name:g.T("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.tP(64);this.H=0;if(!g.MM(g.Y(this.g))){a=
this.g;var b=g.KH(a);b&&(b=b.fo())&&(b=new Q8(a,b),g.M(this,b));b=new P8(a);g.M(this,b);g.aV(a,b.element,4)}},ZDa=function(a,b,c){a.D=c;
a.g.T("presentingplayerstatechange",new g.HP(c,b))},S8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)E8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.Sf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Wb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.sj,index:Math.max(a.g.Pz(),0),currentTime:0==f?void 0:f};(d=HBa(d))&&(c.locationInfo=d);d=c}else d=null;w8("Connecting to: "+g.Ag(b));"cast-selector-receiver"==b.key?(y8(d||null),T7()?Q7().setLaunchParams(d||null):
O7("setLaunchParams called before ready.")):!d&&H8()&&v8()==b.key?g.cG("yt-remote-connection-change",!0):(E8(),y8(d||null),d=u8().ge(),(d=v6(d,b.key))&&F8(d,1))}},oCa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},S6={"'":"\\'"},aEa={},NBa={JW:"atp",d1:"ska",u0:"que",G_:"mus",Z0:"sus",RY:"dsp"};
o6.prototype.Xm=function(){var a=new o6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var B6,x6="",F6=C6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",gCa=C6("loadCastFramework")||C6("loadCastApplicationFramework"),qDa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(I6,g.K);g.h=I6.prototype;g.h.oI=function(a){this.A=arguments;this.g=!1;this.va?this.o=(0,g.F)()+this.cd:this.va=g.ug(this.B,this.cd)};
g.h.stop=function(){this.va&&(g.vg(this.va),this.va=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();I6.aa.V.call(this)};
g.h.pI=function(){this.o?(this.va=g.ug(this.B,this.o-(0,g.F)()),this.o=null):(this.va=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};J6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
J6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=K6.prototype;g.h.Sh=null;g.h.tf=!1;g.h.ik=null;g.h.Ru=null;g.h.Qj=null;g.h.ij=null;g.h.Ug=null;g.h.rh=null;g.h.pi=null;g.h.Oc=null;g.h.Tl=0;g.h.uf=null;g.h.Ap=null;g.h.Vg=null;g.h.Pk=-1;g.h.IC=!0;g.h.Eh=!1;g.h.mr=0;g.h.Lo=null;var mCa={},N6={};g.h=K6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.LT=function(a){a=a.target;var b=this.Lo;b&&3==g.jx(a)?b.gj():this.UD(a)};
g.h.UD=function(a){try{if(a==this.Oc)a:{var b=g.jx(this.Oc),c=this.Oc.l,d=this.Oc.getStatus();if(g.xd&&!g.sc(10)||g.zd&&!g.rc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.ff&&!g.px(this.Oc))break a;this.Eh||4!=b||7==c||(8==c||0>=d?this.g.mf(3):this.g.mf(2));U6(this);var e=this.Oc.getStatus();this.Pk=e;var f=g.px(this.Oc);(this.tf=200==e)?(4==b&&Q6(this),this.C?(nCa(this,b,f),g.ff&&this.tf&&3==b&&(this.A.U(this.l,"tick",this.HT),this.l.start())):P6(this,f),this.tf&&!this.Eh&&(4==b?this.g.yo(this):
(this.tf=!1,M6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Vg=3,O6(13)):(this.Vg=0,O6(14)),Q6(this),R6(this))}}catch(k){this.Oc&&g.px(this.Oc)}finally{}};
g.h.HT=function(){var a=g.jx(this.Oc),b=g.px(this.Oc);this.Tl<b.length&&(U6(this),nCa(this,a,b),this.tf&&4!=a&&M6(this))};
g.h.SS=function(a){T6((0,g.z)(this.RS,this,a),0)};
g.h.RS=function(a){this.Eh||(U6(this),P6(this,a),M6(this))};
g.h.VB=function(a){T6((0,g.z)(this.QS,this,a),0)};
g.h.QS=function(a){this.Eh||(Q6(this),this.tf=a,this.g.yo(this),this.g.mf(4))};
g.h.cancel=function(){this.Eh=!0;Q6(this)};
g.h.jT=function(){this.ik=null;var a=(0,g.F)();0<=a-this.Ru?(2!=this.ij&&this.g.mf(3),Q6(this),this.Vg=2,O6(18),R6(this)):qCa(this,this.Ru-a)};g.h=tCa.prototype;g.h.kr=null;g.h.ne=null;g.h.Mo=!1;g.h.Yx=null;g.h.pn=null;g.h.os=null;g.h.lr=null;g.h.Ie=null;g.h.og=-1;g.h.Ok=null;g.h.pk=null;g.h.connect=function(a){this.lr=a;a=W6(this.g,null,this.lr);O6(3);this.Yx=(0,g.F)();var b=this.g.F;null!=b?(this.Ok=b[0],(this.pk=b[1])?(this.Ie=1,uCa(this)):(this.Ie=2,Y6(this))):(n6(a,"MODE","init"),this.ne=new K6(this,void 0,void 0,void 0),this.ne.Sh=this.kr,L6(this.ne,a,!1,null,!0),this.Ie=0)};
g.h.BH=function(a){if(a)this.Ie=2,Y6(this);else{O6(4);var b=this.g;b.Ff=b.Kg.og;e7(b,9)}a&&this.mf(2)};
g.h.Gq=function(a){return this.g.Gq(a)};
g.h.abort=function(){this.ne&&(this.ne.cancel(),this.ne=null);this.og=-1};
g.h.Xx=function(){return!1};
g.h.OB=function(a,b){this.og=a.Pk;if(0==this.Ie)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Ff=this.og;e7(c,2);return}this.Ok=c[0];this.pk=c[1]}else c=this.g,c.Ff=this.og,e7(c,2);else if(2==this.Ie)if(this.Mo)O6(7),this.os=(0,g.F)();else if("11111"==b){if(O6(6),this.Mo=!0,this.pn=(0,g.F)(),c=this.pn-this.Yx,!g.xd||g.sc(10)||500>c)this.og=200,this.ne.cancel(),O6(12),X6(this.g,this,!0)}else O6(8),this.pn=this.os=(0,g.F)(),this.Mo=!1};
g.h.yo=function(){this.og=this.ne.Pk;if(this.ne.tf)0==this.Ie?this.pk?(this.Ie=1,uCa(this)):(this.Ie=2,Y6(this)):2==this.Ie&&((!g.xd||g.sc(10)?!this.Mo:200>this.os-this.pn)?(O6(11),X6(this.g,this,!1)):(O6(12),X6(this.g,this,!0)));else{0==this.Ie?O6(9):2==this.Ie&&O6(10);var a=this.g;a.Ff=this.og;e7(a,2)}};
g.h.Ml=function(){return this.g.Ml()};
g.h.isActive=function(){return this.g.isActive()};
g.h.mf=function(a){this.g.mf(a)};g.h=Z6.prototype;g.h.Ak=null;g.h.Sd=null;g.h.sc=null;g.h.jr=null;g.h.un=null;g.h.qw=null;g.h.En=null;g.h.yl=0;g.h.HO=0;g.h.od=null;g.h.Mg=null;g.h.jg=null;g.h.Ih=null;g.h.Kg=null;g.h.zp=null;g.h.xj=-1;g.h.bz=-1;g.h.Ff=-1;g.h.Wi=0;g.h.Ji=0;g.h.Gh=8;var f7=new g.Ff;g.A(wCa,g.df);g.A(xCa,g.df);g.A(yCa,g.df);g.h=Z6.prototype;g.h.connect=function(a,b,c,d,e){O6(0);this.jr=b;this.Ak=c||{};d&&g.t(e)&&(this.Ak.OSID=d,this.Ak.OAID=e);this.C?(T6((0,g.z)(this.Mw,this,a),100),CCa(this)):this.Mw(a)};
g.h.Mw=function(a){this.Kg=new tCa(this);this.Kg.kr=null;this.Kg.l=this.B;this.Kg.connect(a)};
g.h.Xx=function(){return 0==this.g};
g.h.TB=function(a){this.Mg=null;FCa(this,a)};
g.h.SB=function(){this.jg=null;this.sc=new K6(this,this.o,"rpc",this.D);this.sc.Sh=null;this.sc.mr=0;var a=this.qw.clone();g.Hm(a,"RID","rpc");g.Hm(a,"SID",this.o);g.Hm(a,"CI",this.zp?"0":"1");g.Hm(a,"AID",this.xj);$6(this,a);if(!g.xd||g.sc(10))g.Hm(a,"TYPE","xmlhttp"),L6(this.sc,a,!0,this.En,!1);else{g.Hm(a,"TYPE","html");var b=this.sc,c=!!this.En;b.ij=3;b.Ug=m6(a.clone());pCa(b,c)}};
g.h.OB=function(a,b){if(0!=this.g&&(this.sc==a||this.Sd==a))if(this.Ff=a.Pk,this.Sd==a&&3==this.g)if(7<this.Gh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.ya(c)&&3==c.length)if(0==c[0])a:{if(!this.jg){if(this.sc)if(this.sc.Qj+3E3<this.Sd.Qj)b7(this),this.sc.cancel(),this.sc=null;else break a;d7(this);O6(19)}}else this.bz=c[1],0<this.bz-this.xj&&37500>c[2]&&this.zp&&0==this.Ji&&!this.Ih&&(this.Ih=T6((0,g.z)(this.kP,this),6E3));else e7(this,11)}else b!=aEa.MX.g&&e7(this,11);else if(this.sc==a&&
b7(this),!g.D(b)){c=this.B.parse(b);g.ya(c);for(var d=0;d<c.length;d++){var e=c[d];this.xj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.En=e[2],e=e[3],null!=e?this.Gh=e:this.Gh=6,this.g=3,this.od&&this.od.Cw(),this.qw=W6(this,this.Ml()?this.En:null,this.jr),GCa(this)):"stop"==e[0]&&e7(this,7):3==this.g&&("stop"==e[0]?e7(this,7):"noop"!=e[0]&&this.od&&this.od.Bw(e),this.Ji=0)}}};
g.h.kP=function(){null!=this.Ih&&(this.Ih=null,this.sc.cancel(),this.sc=null,d7(this),O6(20))};
g.h.yo=function(a){if(this.sc==a){b7(this);this.sc=null;var b=2}else if(this.Sd==a)this.Sd=null,b=1;else return;this.Ff=a.Pk;if(0!=this.g)if(a.tf)1==b?(b=(0,g.F)()-a.Qj,f7.dispatchEvent(new xCa(f7,a.pi?a.pi.length:0,b,this.Wi)),a7(this),this.A.length=0):GCa(this);else{var c=a.Vg,d;if(!(d=3==c||7==c||0==c&&0<this.Ff)){if(d=1==b)this.Sd||this.Mg||1==this.g||2<=this.Wi?d=!1:(this.Mg=T6((0,g.z)(this.TB,this,a),HCa(this,this.Wi)),this.Wi++,d=!0);d=!(d||2==b&&d7(this))}if(d)switch(c){case 1:e7(this,5);
break;case 4:e7(this,10);break;case 3:e7(this,6);break;case 7:e7(this,12);break;default:e7(this,2)}}};
g.h.WH=function(a){if(!g.Pa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.GU=function(a){a?O6(2):(O6(1),ICa(this,8))};
g.h.Gq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.dx;a.F=!1;return a};
g.h.isActive=function(){return!!this.od&&this.od.isActive(this)};
g.h.mf=function(a){f7.dispatchEvent(new yCa(f7,a))};
g.h.Ml=function(){return!(!g.xd||g.sc(10))};
g.h=JCa.prototype;g.h.Cw=function(){};
g.h.Bw=function(){};
g.h.Aw=function(){};
g.h.tq=function(){};
g.h.Fx=function(){return{}};
g.h.isActive=function(){return!0};g.A(g7,g.K);g.h=g7.prototype;g.h.JS=function(){this.cd=Math.min(3E5,2*this.cd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.cd+15E3*Math.random();g.$t(this.g,a);this.l=(0,g.F)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.cd=5E3};g.A(h7,JCa);g.h=h7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Ld=function(a){return this.o.Ld(a)};
g.h.T=function(a,b){return this.o.T.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.bf(this.o),MCa(this),g.bf(this.l),this.l=null)};
g.h.ha=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new Z6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.g;e&&(e.od=null);d.od=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.xj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):i7(this)&&DCa(this.g,c)};
g.h.Cw=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)DCa(this.g,a[b])}this.T("handlerOpened")};
g.h.Aw=function(a){var b=2==a&&401==this.g.Ff;4==a||b||this.l.start();this.T("handlerError",a)};
g.h.tq=function(a){if(!this.l.isActive())this.T("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Fx=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.ec(a,this.B);return a};
g.h.Bw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),BCa(this.g)):this.T("handlerMessage",new KCa(a[0],a[1]))};
g.h.nV=function(){this.l.isActive();var a=this.g,b=0;a.sc&&b++;a.Sd&&b++;0!=b||this.connect(this.B,this.A)};j7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
j7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
j7.prototype.B=function(a){a(Error("request timed out"))};var UCa=(0,g.F)(),m7=null,p7=Array(50),o7=-1,q7=!1;g.A(r7,g.NF);r7.prototype.ge=function(){return this.g};
r7.prototype.contains=function(a){return!!u6(this.g,a)};
r7.prototype.get=function(a){return a?v6(this.g,a):null};
r7.prototype.info=function(a){n7(this.D,a)};g.A(s7,g.NF);var bEa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=s7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.va)&&this.ZD()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.va)||(g.XD(this.va),this.va=window.NaN)};
g.h.V=function(){this.stop();s7.aa.V.call(this)};
g.h.ZD=function(){this.va=window.NaN;this.g=g.kE(k7(this.C,"/pairing/get_screen"),{method:"POST",Jb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.z)(this.pV,this),onError:(0,g.z)(this.oV,this),td:(0,g.z)(this.qV,this)})};
g.h.pV=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.T("pairingComplete",new p6(c))};
g.h.oV=function(a){this.g=null;a.status&&404==a.status?this.l>=bEa.length?this.T("pairingFailed",Error("DIAL polling timed out")):(a=bEa[this.l],this.va=g.VD((0,g.z)(this.ZD,this),a),this.l++):this.T("pairingFailed",Error("Server error "+a.status))};
g.h.qV=function(){this.g=null;this.T("pairingFailed",Error("Server not responding"))};g.A(u7,r7);g.h=u7.prototype;g.h.start=function(){t7(this)&&this.T("screenChange");!g.UG("yt-remote-lounge-token-expiration")&&YCa(this);g.XD(this.l);this.l=g.VD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){t7(this);VCa(this,a);v7(this,!1);this.T("screenChange");b(a);a.token||YCa(this)};
g.h.remove=function(a,b){var c=t7(this);XCa(this,a)&&(v7(this,!1),c=!0);b(a);c&&this.T("screenChange")};
g.h.up=function(a,b,c,d){var e=t7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,v7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.T("screenChange")};
g.h.V=function(){g.XD(this.l);u7.aa.V.call(this)};
g.h.CI=function(a){t7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}v7(this,!b);b&&n7(this.D,"Missed "+b+" lounge tokens.")};
g.h.BI=function(a){n7(this.D,"Requesting lounge tokens failed: "+a)};g.A(x7,g.NF);g.h=x7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.UG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.F)()-144E5<a?0:a)?z7(this):(this.A=(0,g.F)()+3E5,g.TG("yt-remote-fast-check-period",this.A),this.hu())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){w7("Updating availability on schedule.");var a=this.C(),b=g.Kb(this.g,function(b,d){return b&&!!v6(a,d)},this);
y7(this,b)};
g.h.V=function(){g.XD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);x7.aa.V.call(this)};
g.h.hu=function(){g.XD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=aDa(this);if(g.Ob(a)){var b=k7(this.B,"/pairing/get_screen_availability");this.l=l7(this.B,b,{lounge_token:g.Qb(a).join(",")},(0,g.z)(this.pS,this,a),(0,g.z)(this.oS,this))}else y7(this,{}),z7(this)};
g.h.pS=function(a,b){this.l=null;var c=g.Qb(aDa(this));if(g.ib(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;y7(this,d);z7(this)}else this.bc("Changing Screen set during request."),this.hu()};
g.h.oS=function(a){this.bc("Screen availability failed: "+a);this.l=null;z7(this)};
g.h.bc=function(a){n7("OnlineScreenService",a)};g.A(A7,r7);g.h=A7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.T("screenChange"),this.l.isEmpty()||this.T("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.up=function(a,b,c,d){this.o.contains(a)?this.o.up(a,b,c,d):(a="Updating name of unknown screen: "+a.name,n7(this.D,a),d(Error(a)))};
g.h.ge=function(a){return a?this.g:g.Wa(this.g,(0,g.Kd)(this.A,function(a){return!this.contains(a)},this))};
g.h.aE=function(){return(0,g.Kd)(this.ge(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.bE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new s7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.bf(f);d(B7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.bf(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.sV=function(a,b,c,d){g.kE(k7(this.C,"/pairing/get_screen"),{method:"POST",Jb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(a,d){var e=new p6(d.screen||{});if(!e.name||eDa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);eDa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(B7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
td:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.bf(this.o);g.bf(this.l);A7.aa.V.call(this)};
g.h.SI=function(){fDa(this);this.T("screenChange");this.l.update()};
A7.prototype.dispose=A7.prototype.dispose;g.A(D7,g.NF);g.h=D7.prototype;g.h.zo=function(a){this.o=a;this.T("sessionScreen",this.o)};
g.h.ke=function(a){this.ha()||(a&&E7(this,""+a),this.o=null,this.T("sessionScreen",null))};
g.h.info=function(a){n7(this.L,a)};
g.h.dE=function(){return null};
g.h.ou=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){E7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.ou("");D7.aa.V.call(this)};g.A(F7,D7);g.h=F7.prototype;g.h.nu=function(a){if(this.g){if(this.g==a)return;E7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);hDa(this)};
g.h.zj=function(a){this.info("launchWithParams no-op for Cast: "+g.Ag(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.ke()},this),(0,g.z)(function(){this.ke(Error("Failed to stop receiver app."))},this)):this.ke(Error("Stopping cast device witout session."))};
g.h.ou=g.y;g.h.V=function(){this.info("disposeInternal");g.XD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;F7.aa.V.call(this)};
g.h.vT=function(a,b){if(!this.ha())if(b){var c=g.Yw(b);if(g.Ba(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ag(c));switch(d){case "mdxSessionStatus":gDa(this,c.screenId);break;default:E7(this,"Unknown youtube message: "+d)}}else E7(this,"Unable to parse message.")}else E7(this,"No data in message.")};
g.h.Qx=function(a,b,c,d){dDa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(E7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.VD((0,g.z)(this.Qx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.dE=function(){return this.g};
g.h.tV=function(a){this.ha()||a||(E7(this,"Cast session died."),this.ke())};g.A(G7,D7);g.h=G7.prototype;g.h.nu=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.zj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.XD(this.C);this.A?this.A.stop((0,g.z)(this.ke,this,null),(0,g.z)(this.ke,this,"Failed to stop DIAL device.")):this.ke()};
g.h.V=function(){this.g();this.g=g.y;g.XD(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;G7.aa.V.call(this)};
g.h.wV=function(a){this.ha()||a||(E7(this,"DIAL session died."),this.g(),this.g=g.y,this.ke())};
g.h.Ur=function(a){this.I=t6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,jDa(this));a(b);iDa(this)}else this.D=(0,g.z)(function(){g.XD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,jDa(this));a(b);iDa(this)},this),this.C=g.VD((0,g.z)(function(){this.D()},this),100)};
g.h.hK=function(a,b,c){dDa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.zo(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Ur(b,c)},this),(0,g.z)(function(a){E7(this,"Failed to get DIAL screen: "+a);
this.Ur(b,c)},this))};g.A(H7,D7);H7.prototype.stop=function(){this.ke()};
H7.prototype.nu=g.y;H7.prototype.zj=function(){g.XD(this.g);this.g=window.NaN;var a=v6(this.H.ge(),this.l.label);a?this.zo(a):this.ke(Error("No such screen"))};
H7.prototype.V=function(){g.XD(this.g);this.g=window.NaN;H7.aa.V.call(this)};g.A(I7,g.NF);g.h=I7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.PB,this),(0,g.z)(this.ZR,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.UP,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),RCa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.cE,this)),this.o=lDa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.bc("Failed to set initial custom receivers: "+g.Ag(a))},this)),this.T("yt-remote-cast2-availability-change",K7(this)),b(!0))},this),(0,g.z)(function(a){this.bc("Failed to initialize API: "+g.Ag(a));
b(!1)},this))};
g.h.qU=function(a,b){J7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)J7("Unsetting old screen status: "+this.g.l.friendlyName),L7(this,null)}if(a&&b){if(!this.g){c=v6(this.l.ge(),a);if(!c){J7("setConnectedScreenStatus: Unknown screen.");return}var d=kDa(this,c);d||(J7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.bc("Failed to set initial custom receivers: "+g.Ag(a))},this)));
J7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);L7(this,new H7(this.l,d),!0)}this.g.ou(b)}else J7("setConnectedScreenStatus: no screen.")};
g.h.rU=function(a){this.ha()?this.bc("Setting connection data on disposed cast v2"):this.g?this.g.zj(a):this.bc("Setting connection data without a session")};
g.h.vV=function(){this.ha()?this.bc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),L7(this,null)):J7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.PB,this),(0,g.z)(this.uS,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.cE,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ua(g.x("yt.mdx.remote.debug.handlers_")||[],OCa);g.bf(this.g);I7.aa.V.call(this)};
g.h.bc=function(a){n7("Controller",a)};
g.h.QB=function(a,b){this.g==a&&(b||L7(this,null),this.T("yt-remote-cast2-session-change",b))};
g.h.VR=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),J7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)J7("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{J7("onReceiverAction_: Casting to active receiver.");this.g.o&&this.T("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:L7(this,
new H7(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:L7(this,new G7(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:L7(this,new F7(this.l,a));break;default:this.bc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.bc("Stopping receiver w/o session: "+a.friendlyName)}else this.bc("onReceiverAction_ called without receiver.")};
g.h.UP=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.bc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.bc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return J7("Reselecting dial screen."),
this.T("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.bc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);L7(this,new G7(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.hK,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.Ur,b))};
g.h.PB=function(a){if(!this.ha()){J7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)J7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),L7(this,new F7(this.l,b),!0);else{this.bc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=v6(this.l.ge(),c.label);
d&&q6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(J7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.bf(this.g),this.g=new F7(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.QB,this,this.g)),this.g.zj(null));this.g.nu(a)}}};
g.h.uV=function(){return this.g?this.g.dE():null};
g.h.uS=function(a){this.ha()||(this.bc("Failed to estabilish a session: "+g.Ag(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&L7(this,null))};
g.h.ZR=function(a){J7("Receiver availability updated: "+a);if(!this.ha()){var b=K7(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;K7(this)!=b&&this.T("yt-remote-cast2-availability-change",K7(this))}};
g.h.cE=function(){this.ha()||(this.o=lDa(this),J7("Updating custom receivers: "+g.Ag(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.bc("Failed to set custom receivers.")},this)),this.T("yt-remote-cast2-availability-change",K7(this)))};
I7.prototype.setLaunchParams=I7.prototype.rU;I7.prototype.setConnectedScreenStatus=I7.prototype.qU;I7.prototype.stopSession=I7.prototype.vV;I7.prototype.getCastSession=I7.prototype.uV;I7.prototype.requestSession=I7.prototype.requestSession;I7.prototype.init=I7.prototype.init;I7.prototype.dispose=I7.prototype.dispose;var R7=[];g.h=W7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";X7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.If=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.gb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+Y7(this):this.H};
g.h.clone=function(){return new W7(b8(this))};g.A(d8,g.NF);g.h=d8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,j8(this,"play")):i8(this,"play"),h8(this,1,$7(e8(this))),this.T("remotePlayerChange")):f8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,j8(this,"pause")):i8(this,"pause"),h8(this,2,$7(e8(this))),this.T("remotePlayerChange")):f8(this,this.pause)};
g.h.YD=function(a){if(1==this.g){if(this.l){var b=e8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.gb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,j8(this,"seekTo",{newTime:a}))}else i8(this,"seekTo",{newTime:a});h8(this,3,a);this.T("remotePlayerChange")}else f8(this,g.Ea(this.YD,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,j8(this,"stopVideo")):i8(this,"stopVideo");var a=e8(this);a.index=-1;a.videoId="";X7(a);g8(this,a);this.T("remotePlayerChange")}else f8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=e8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){n7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.bc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){n7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.bc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);i8(this,"setVolume",e)}c.muted=b;c.volume=a;g8(this,c)}else f8(this,g.Ea(this.setVolume,a,b))};
g.h.bD=function(a,b){if(1==this.g){var c=e8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Ag(b.style),g.ec(d,c.l));i8(this,"setSubtitlesTrack",d);g8(this,c)}else f8(this,g.Ea(this.bD,a,b))};
g.h.Wu=function(a,b){if(1==this.g){i8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Nb.id});var c=e8(this);c.audioTrackId=b.Nb.id;g8(this,c)}else f8(this,g.Ea(this.Wu,a,b))};
g.h.XD=function(a,b){if(1==this.g){if(a&&b){var c=e8(this);a8(c,a,b);g8(this,c)}i8(this,"previous")}else f8(this,g.Ea(this.XD,a,b))};
g.h.WD=function(a,b){if(1==this.g){if(a&&b){var c=e8(this);a8(c,a,b);g8(this,c)}i8(this,"next")}else f8(this,g.Ea(this.WD,a,b))};
g.h.gx=function(){1==this.g?i8(this,"dismissAutoplay"):f8(this,this.gx)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.T("proxyStateChange",a,this.g)}d8.aa.dispose.call(this)};
g.h.V=function(){yDa(this);this.A=null;this.B.clear();c8(this,null);d8.aa.V.call(this)};
g.h.Xu=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.T("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.oC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.QR=function(a,b){this.T(a,b)};
g.h.rP=function(a){if(!a)this.Bl(null),c8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=e8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)n7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,g8(this,b)}};
g.h.Bl=function(a){n7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),zDa(this),this.T("remotePlayerChange")};
g.h.qP=function(a){a?(zDa(this),this.T("remotePlayerChange")):this.Bl(null)};
g.h.DP=function(){var a=vDa();a&&c8(this,a)};
g.h.bc=function(a){n7("CP",a)};g.A(k8,g.NF);g.h=k8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Va.listId=c);this.Va.videoId=d;this.Va.index=k||0;this.Va.state=3;Z7(this.Va,m);this.A="UNSUPPORTED";l8("Connecting with setPlaylist and params: "+g.Ag(l));this.g.connect({method:"setPlaylist",
params:g.Ag(l)},a,VBa())}else l8("Connecting without params"),this.g.connect({},a,VBa());BDa(this)};
g.h.dispose=function(){this.ha()||(this.T("beforeDispose"),m8(this,3));k8.aa.dispose.call(this)};
g.h.V=function(){n8(this);p8(this);o8(this);g.XD(this.H);this.H=window.NaN;g.XD(this.I);this.I=window.NaN;this.o=null;g.xF(this.R);this.R.length=0;this.g.dispose();k8.aa.V.call(this);this.A=this.D=this.l=this.Va=this.g=null};
g.h.tI=function(){this.C(2)};
g.h.vP=function(){l8("Channel opened");this.N&&(this.N=!1,o8(this),this.L=g.VD((0,g.z)(function(){l8("Timing out waiting for a screen.");this.C(1)},this),15E3));
ZBa(LCa(this.g),this.Y)};
g.h.sP=function(){l8("Channel closed");(0,window.isNaN)(this.B)?A6(!0):A6();this.dispose()};
g.h.tP=function(a){A6();(0,window.isNaN)(this.F())?(l8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,l8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),m8(this,2))};
g.h.uP=function(a){a.params?l8("Received: action="+a.action+", params="+g.Ag(a.params)):l8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Yw(a.params.devices);this.l=(0,g.G)(a,function(a){return new o6(a)});
a=!!g.La(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
EDa(this,a);break;case "loungeScreenDisconnected":g.Va(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
EDa(this,!1);break;case "remoteConnected":var b=new o6(g.Yw(a.params.device));g.La(this.l,function(a){return b?a.id==b.id:!1})||g.Sa(this.l,b);
break;case "remoteDisconnected":b=new o6(g.Yw(a.params.device));g.Va(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":GDa(this,a);break;case "nowPlaying":IDa(this,a);break;case "onStateChange":HDa(this,a);break;case "onAdStateChange":JDa(this,a);break;case "onVolumeChanged":KDa(this,a);break;case "onSubtitlesTrackChanged":FDa(this,a);break;case "nowAutoplaying":LDa(this,a);break;case "autoplayDismissed":this.T("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.T("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.T("autoplayModeChange",this.A);"DISABLED"==this.A&&this.T("autoplayDismissed");break;case "onHasPreviousNextChanged":MDa(this,a);break;case "requestAssistedSignIn":this.T("assistedSignInRequested",a.params.authCode);break;default:l8("Unrecognized action: "+a.action)}};
g.h.aU=function(){if(this.o){var a=this.o;this.o=null;this.Va.videoId!=a&&q8(this,"getNowPlaying")}};
k8.prototype.subscribe=k8.prototype.subscribe;k8.prototype.unsubscribeByKey=k8.prototype.Ld;k8.prototype.ea=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.F())?i7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
k8.prototype.getProxyState=k8.prototype.ea;k8.prototype.C=function(a){l8("Disconnecting with "+a);n8(this);this.T("beforeDisconnect",a);1==a&&A6();MCa(this.g,a);this.dispose()};
k8.prototype.disconnect=k8.prototype.C;k8.prototype.da=function(){var a=this.Va;this.o&&(a=this.Va.clone(),a8(a,this.o,a.index));return b8(a)};
k8.prototype.getPlayerContextData=k8.prototype.da;
k8.prototype.ia=function(a){var b=new W7(a);b.videoId&&b.videoId!=this.Va.videoId&&(this.o=b.videoId,g.XD(this.H),this.H=g.VD((0,g.z)(this.aU,this),5E3));var c=[];this.Va.listId==b.listId&&this.Va.videoId==b.videoId&&this.Va.index==b.index||c.push("remoteQueueChange");this.Va.g==b.g&&this.Va.volume==b.volume&&this.Va.muted==b.muted&&$7(this.Va)==$7(b)&&g.Ag(this.Va.l)==g.Ag(b.l)||c.push("remotePlayerChange");this.Va.reset(a);(0,g.B)(c,function(a){this.T(a)},this)};
k8.prototype.setPlayerContextData=k8.prototype.ia;k8.prototype.W=function(){var a=this.g.C.id,b=g.La(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
k8.prototype.getOtherConnectedRemoteId=k8.prototype.W;k8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.F)():window.NaN};
k8.prototype.getReconnectTimeout=k8.prototype.F;k8.prototype.X=function(){return this.A||"UNSUPPORTED"};
k8.prototype.getAutoplayMode=k8.prototype.X;k8.prototype.Z=function(){return this.D||""};
k8.prototype.getAutoplayVideoId=k8.prototype.Z;k8.prototype.oa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.au(a.g);a.start()}};
k8.prototype.reconnect=k8.prototype.oa;k8.prototype.fa=function(a,b){q8(this,a,b);DDa(this)};
k8.prototype.sendMessage=k8.prototype.fa;g.A(r8,r7);g.h=r8.prototype;g.h.ge=function(a){return this.bd.$_gs(a)};
g.h.contains=function(a){return!!this.bd.$_c(a)};
g.h.get=function(a){return this.bd.$_g(a)};
g.h.start=function(){this.bd.$_st()};
g.h.add=function(a,b,c){this.bd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.bd.$_r(a,b,c)};
g.h.up=function(a,b,c,d){this.bd.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.bd.$_ubk(this.l[a]);this.l.length=0;this.bd=null;r8.aa.V.call(this)};
g.h.rV=function(){this.T("screenChange")};
g.h.qR=function(){this.T("onlineScreenChange")};
A7.prototype.$_st=A7.prototype.start;A7.prototype.$_gspc=A7.prototype.sV;A7.prototype.$_gsppc=A7.prototype.bE;A7.prototype.$_c=A7.prototype.contains;A7.prototype.$_g=A7.prototype.get;A7.prototype.$_a=A7.prototype.add;A7.prototype.$_un=A7.prototype.up;A7.prototype.$_r=A7.prototype.remove;A7.prototype.$_gs=A7.prototype.ge;A7.prototype.$_gos=A7.prototype.aE;A7.prototype.$_s=A7.prototype.subscribe;A7.prototype.$_ubk=A7.prototype.Ld;var s8=null,t8=null,I8=null,x8=[];g.p(J8,g.K);g.h=J8.prototype;
g.h.V=function(){g.K.prototype.V.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.NB,this);this.g.unsubscribe("remotePlayerChange",this.El,this);this.g.unsubscribe("remoteQueueChange",this.Ao,this);this.g.unsubscribe("autoplayUpNext",this.kB,this);this.g.unsubscribe("previousNextChange",this.KB,this);this.g.unsubscribe("nowAutoplaying",this.CB,this);this.g.unsubscribe("autoplayDismissed",this.jB,this);this.g=this.F=null};
g.h.kA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(M8(this)){if(!e8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":e8(this.g).gb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.gj(c[0],c[1]);break;case "control_subtitles_set_track":N8(this,c[0]);break;case "control_set_audio_track":c=c[0],M8(this)&&this.g.Wu(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();O8(this,0==c?void 0:c);break;case "control_seek":O8(this,c[0]);break;case "control_subtitles_set_track":N8(this,c[0]);break;case "control_set_audio_track":c=c[0],M8(this)&&this.g.Wu(this.l.getVideoData(1).videoId,c)}};
g.h.pP=function(a){this.K.oI(a)};
g.h.UU=function(a){this.kA("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.pD=function(){var a=this.l.uc("captions","track");g.Xb(a)||N8(this,a)};
g.h.AB=function(a){if(M8(this)){this.g.unsubscribe("remotePlayerChange",this.El,this);var b=Math.round(a.volume);a=!!a.muted;var c=e8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.L.start();this.g.subscribe("remotePlayerChange",this.El,this)}};
g.h.JQ=function(){g.Xb(this.C)||YDa(this,this.C);this.D=!1};
g.h.NB=function(a,b){this.B.stop();2==b&&this.mD()};
g.h.El=function(){if(M8(this)){this.A.stop();var a=e8(this.g);switch(a.g){case 1081:case 1:L8(this,new g.tP(8));this.lD();break;case 1085:case 3:L8(this,new g.tP(9));break;case 1083:case 0:L8(this,new g.tP(2));this.I.stop();K8(this,this.l.getVideoData().lengthSeconds);break;case 1084:L8(this,new g.tP(4));break;case 2:L8(this,new g.tP(4));K8(this,$7(a));break;case -1:L8(this,new g.tP(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.T("YTP_MDX_PLAYER_ERROR")},L8(this,new g.tP(128,a))}a=
e8(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,YDa(this,a));a=e8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.L.isActive()||this.MD()}else XDa(this)};
g.h.KB=function(){this.l.T("mdxpreviousnextchange")};
g.h.Ao=function(){M8(this)||XDa(this)};
g.h.AH=function(){this.g.gx()};
g.h.kB=function(a){a&&(a=g.kE("/watch_queue_ajax",{method:"GET",Vc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.WS,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.WS=function(a,b){var c=new g.jO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.T("mdxautoplayupnext",c)};
g.h.CB=function(a){(0,window.isNaN)(a)||this.l.T("mdxnowautoplaying",a)};
g.h.jB=function(){this.l.T("mdxautoplaycanceled")};
g.h.pN=function(a,b){-1==e8(this.g).g?O8(this,a):b&&this.g.YD(a)};
g.h.MD=function(){if(M8(this)){var a=e8(this.g);this.o.Aa(this.R);a.muted?this.l.mute():this.l.Tf();this.l.setVolume(a.volume);this.R=this.o.O(this.l,"onVolumeChange",this.AB)}};
g.h.lD=function(){this.A.stop();if(!this.g.ha()){var a=e8(this.g);a.gb()&&L8(this,new g.tP(8));K8(this,$7(a));this.A.start()}};
g.h.mD=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(P8,g.V);P8.prototype.B=function(a){$Da(this,a.state)};g.p(Q8,g.KZ);Q8.prototype.K=function(){var a=this.o.uc("remote","receivers");a&&1<a.length&&!this.o.uc("remote","quickCast")?(this.H=g.kb(a,this.C,this),g.LZ(this,(0,g.G)(a,this.C)),a=this.o.uc("remote","currentReceiver"),this.lf(this.C(a)),this.enable(!0)):this.enable(!1)};
Q8.prototype.C=function(a){return a.key};
Q8.prototype.kf=function(a){return"cast-selector-receiver"==a?g.T("YTP_MDX_CAST_SELECTOR"):this.H[a].name};
Q8.prototype.rd=function(a){g.KZ.prototype.rd.call(this,a);this.o.Id("remote","currentReceiver",this.H[a]);this.B.Ob()};g.p(R8,g.gV);g.h=R8.prototype;g.h.create=function(){RDa(g.zM(g.Y(this.g)));this.C.push(g.ZF("yt-remote-before-disconnect",this.lP,this));this.C.push(g.ZF("yt-remote-connection-change",this.aS,this));this.C.push(g.ZF("yt-remote-receiver-availability-change",this.LB,this));this.C.push(g.ZF("yt-remote-auto-connect",this.YR,this));this.C.push(g.ZF("yt-remote-receiver-resumed",this.XR,this));this.LB()};
g.h.load=function(){this.g.Us();g.gV.prototype.load.call(this);this.B=new J8(this,this.g,this.l);var a=(a=WDa())?a.currentTime:0;var b=H8()?new d8(C8(),void 0):null;0==a&&b&&(a=$7(e8(b)));0!=a&&(this.H=a||0,this.g.T("progresssync",a,void 0));ZDa(this,this.D,this.D);g.$_(this.g.app,6)};
g.h.unload=function(){this.g.T("mdxautoplaycanceled");this.A=this.o;g.cf(this.B,this.l);this.l=this.B=null;g.gV.prototype.unload.call(this);g.$_(this.g.app,5)};
g.h.V=function(){g.$F(this.C);g.gV.prototype.V.call(this)};
g.h.tl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.kA.apply(this.B,[a].concat(g.pa(c)))};
g.h.kI=function(){return this.loaded?this.B.suggestion:null};
g.h.If=function(){return this.l?e8(this.l).If:!1};
g.h.hasNext=function(){return this.l?e8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.dN=function(){var a=e8(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.dd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+Y7(a):a.A,isPeggedToLive:1>=(a.C?a.o+Y7(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+Y7(a):a.o,seekableStart:0<a.B?a.B+Y7(a):a.B}};
g.h.eN=function(){this.l&&this.l.WD()};
g.h.fN=function(){this.l&&this.l.XD()};
g.h.lP=function(a){1==a&&(this.I=this.l?e8(this.l):null)};
g.h.aS=function(){var a=H8()?new d8(C8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.bf(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.getVideoData().videoId&&this.g.Nz(a.videoId,$7(a)));this.g.T("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.LB=function(){this.F=[this.o].concat(TDa());var a=D8()||this.o;S8(this,a);this.g.ra("onMdxReceiversChange")};
g.h.YR=function(){var a=D8();S8(this,a)};
g.h.XR=function(){this.A=D8()};
g.h.cN=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?U7():S8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&U7(),!0):!1}};
g.h.gN=function(){i8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Lc=function(){return!1};g.ZX.remote=R8;})(_yt_player);
